Init project
RenZorRUS/gpm-frontend pull request #1
Opened 2024-09-21 20:54 UTC by Sydnes2003

2024-09-21 21:58 UTC, RenZorRUS requested changes

2024-09-21 21:58 UTC, RenZorRUS commented on README.md
> +Gamified Personal Manager (GPM) - is an app designed to enhance productivity and personal growth through gamification principles. By transforming daily tasks and goals into engaging challenges, GPM e
Please describe the project in detail here or at least provide high-level information: what libraries it uses, how to install and run it

2024-09-21 21:58 UTC, RenZorRUS commented on package.json
> +  "devDependencies": {
Please add [Husky](https://typicode.github.io/husky/) pre-commit checker to automatically check code format and lint rules before committing

2024-09-21 21:58 UTC, RenZorRUS commented on src/app/providers/router/index.ts
> +export { AppRouter };
Why do we need to store this file containing only two lines `import` and `export`?
I don't quite understand it.

2024-09-21 21:58 UTC, RenZorRUS commented on src/app/App.tsx
> +import ThemeSwitcher from "../widgets/ThemeSwitcher/ui/ThemeSwitcher.tsx";
Could you please change all imports to a single style and avoid relative imports (e.g. relative means `../index.ts` or `../../component.ts`).

2024-09-21 21:58 UTC, RenZorRUS commented on src/app/providers/theme/lib/ThemeContext.ts
> +}
Should we use `const enum` here instead of `enum`?
Docs: https://www.typescriptlang.org/docs/handbook/enums.html#reverse-mappings

2024-09-21 21:58 UTC, RenZorRUS commented on src/app/providers/theme/lib/ThemeContext.ts
> +export const ThemeContext = createContext<ThemeContextProps>({});
Remove `?:` from `ThemeContextProps` and assign default values to the `createContext<ThemeContextProps>({});` function.

2024-09-21 21:58 UTC, RenZorRUS commented on src/app/providers/theme/lib/useTheme.ts
> +    return {theme, toggleTheme} as UseThemeResult;
Remove `as UseThemeResult` from the `return` statement and fix TypeScript issues

2024-09-21 21:58 UTC, RenZorRUS commented on src/app/providers/theme/lib/useTheme.ts
> +        setTheme!(newTheme);
Try to remove `!` from `setTheme!(newTheme);`
Best practice: https://www.reddit.com/r/typescript/comments/wvm3v6/comment/ilfxkn9

2024-09-21 21:58 UTC, RenZorRUS commented on src/app/providers/theme/ui/ThemeProvider.tsx
> +    const [theme, setTheme] = useState<Theme>(defaultTheme);
Should we prefer to use `object destruction` instead of `array destruction`?
Comment: https://stackoverflow.com/questions/66317880/why-is-destructuring-an-array-in-javascript-slower-than-for-an-object

2024-09-21 21:58 UTC, RenZorRUS commented on src/app/styles/reset.scss
> +}
Should we combine them?

2024-09-21 21:58 UTC, RenZorRUS commented on src/main.tsx
> +import './app/styles/index.scss';
Try to avoid relative imports
Article: https://medium.com/@osahonoboite/relative-vs-absolute-imports-in-node-js-d7e562c85f57

2024-09-21 21:58 UTC, RenZorRUS commented on src/shared/config/routeConfig/index.tsx
> +}
Same here, should we use `const enum` instead of `enum`?

2024-09-21 21:58 UTC, RenZorRUS commented on src/shared/ui/Button/ui/Button.tsx
> +}
Same here

2024-09-21 21:58 UTC, RenZorRUS commented on src/shared/ui/Button/ui/Button.tsx
> +    } = props;
Should we move `props` object destruction to the function parameters (ex: `const a = ({ a,b,c }) => {...}`)?

2024-09-21 22:24 UTC, Sydnes2003 commented on package.json
> +  "devDependencies": {
I use eslint, and lint manually. Just updated the rules for it

2024-09-21 22:25 UTC, Sydnes2003 commented on src/app/providers/router/index.ts
> +export { AppRouter };
It's Public API, I use it to make the code modular

2024-09-21 22:25 UTC, Sydnes2003 commented on src/app/App.tsx
> +import ThemeSwitcher from "../widgets/ThemeSwitcher/ui/ThemeSwitcher.tsx";
Fixed

2024-09-21 22:27 UTC, Sydnes2003 commented on src/app/providers/theme/lib/ThemeContext.ts
> +}
It is used in [ThemeSwitcher.tsx](https://github.com/RenZorRUS/gpm-frontend/blob/init-project/src/widgets/ThemeSwitcher/ui/ThemeSwitcher.tsx) component

2024-09-21 22:27 UTC, Sydnes2003 commented on src/app/styles/reset.scss
> +}
Done

2024-09-21 22:29 UTC, Sydnes2003 commented on src/main.tsx
> +import './app/styles/index.scss';
I use relative imports in case the files are on the same slice (refer to "feature-sliced design" architecture)

2024-09-21 22:33 UTC, Sydnes2003 commented on src/shared/ui/Button/ui/Button.tsx
> +}
It is used in [ThemeSwitcher.tsx](https://github.com/RenZorRUS/gpm-frontend/blob/init-project/src/widgets/ThemeSwitcher/ui/ThemeSwitcher.tsx) component

2024-09-21 22:34 UTC, Sydnes2003 commented on src/shared/config/routeConfig/index.tsx
> +}
I was thinking it may be used later in the app. For now I will use `const`, though it might change later

2024-09-21 22:36 UTC, Sydnes2003 commented on src/shared/ui/Button/ui/Button.tsx
> +    } = props;
The expression would then be too bulky. I moved the destructurizing into a separate line for the purpose of code readability

2024-09-21 22:36 UTC, Sydnes2003 commented on README.md
> +Gamified Personal Manager (GPM) - is an app designed to enhance productivity and personal growth through gamification principles. By transforming daily tasks and goals into engaging challenges, GPM e
Done

2024-09-21 22:38 UTC, Sydnes2003 commented on src/app/providers/theme/lib/ThemeContext.ts
> +export const ThemeContext = createContext<ThemeContextProps>({});
Done

2024-09-21 22:38 UTC, Sydnes2003 commented on src/app/providers/theme/lib/useTheme.ts
> +        setTheme!(newTheme);
Done

2024-09-22 05:47 UTC, Sydnes2003 commented on src/app/styles/reset.scss
I was thinking about changing the Header child components to `<li>` elements, for better semantics. It did not work out, the code was bulky, the `list-style: none;` will be gone in the next commit

2024-09-22 05:47 UTC, Sydnes2003 commented on src/shared/assets/icons/logo.svg
Let me know what do you think of this logo for our app

2024-09-22 17:53 UTC, Sydnes2003 commented on package.json
> +  "devDependencies": {
Added Husky

2024-09-22 18:05 UTC, RenZorRUS requested changes

2024-09-22 18:07 UTC, RenZorRUS commented on src/app/providers/theme/lib/ThemeContext.ts
> +    (localStorage.getItem(LOCAL_STORAGE_THEME_KEY) as Theme) || Theme.LIGHT;
Please rename this variable to `camelCase` format as you evaluate its value at runtime
Docs: https://javascript.info/variables#uppercase-const

2024-09-22 18:11 UTC, RenZorRUS commented on src/shared/lib/hooks/useActive/lib/useActive.ts
> +    };
Should we use `useCallback` here?

2024-09-22 18:19 UTC, RenZorRUS approved these changes

2024-09-22 18:19 UTC, merged